name: Compilar Flutter iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Seleccionar versión de Xcode (Xcode 16.1)
        run: |
          sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
          xcodebuild -version

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias de Flutter
        run: flutter pub get

      - name: Preparar entorno nativo de iOS
        run: |
          cd ios
          pod repo update
          pod install

      - name: Compilar App para iOS
        # Quitamos la limpieza agresiva y dejamos que Flutter gestione la creación de carpetas automáticamente
        run: flutter build ios --release --no-codesign
        
      - name: Subir el resultado de la compilación
        uses: actions/upload-artifact@v4
        with:
          name: App-iOS-Build
          path: build/ios/iphoneos